name: Deploy to DigitalOcean Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clear known_hosts
      env:
        HOST_IP: ${{ secrets.HOST_IP }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${HOST_IP} '
          > ~/.ssh/known_hosts
        '

    - name: Deploy to DigitalOcean Server
      env:
        HOST_IP: ${{ secrets.HOST_IP }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${HOST_IP} '
          cd /path/to/your/application
          git pull
          # Any additional commands to build/restart your application
        '